# Generated by Django 4.2 on 2025-06-17 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_leader_project_company_projecttype_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arealeader',
            options={'verbose_name': 'Lider del area', 'verbose_name_plural': 'Lideres de las areas'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-start_date'], 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AlterModelOptions(
            name='projectarea',
            options={'verbose_name': 'Area de proyecto', 'verbose_name_plural': 'Areas de proyectos'},
        ),
        migrations.AlterModelOptions(
            name='projectareamember',
            options={'verbose_name': 'Miembro del area', 'verbose_name_plural': 'Miembros de las areas'},
        ),
        migrations.AlterModelOptions(
            name='projectleader',
            options={'verbose_name': 'Lider de proyecto', 'verbose_name_plural': 'Lideres de proyectos'},
        ),
        migrations.AlterModelOptions(
            name='projectpriority',
            options={'verbose_name': 'Prioridad', 'verbose_name_plural': 'Prioridades'},
        ),
        migrations.AlterModelOptions(
            name='projectstate',
            options={'verbose_name': 'Estado de proyecto', 'verbose_name_plural': 'Estados de proyectos'},
        ),
        migrations.AlterModelOptions(
            name='projecttype',
            options={'verbose_name': 'Tipo de proyecto', 'verbose_name_plural': 'Tipos de proyectos'},
        ),
    ]
