# Generated by Django 4.2 on 2025-06-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Modelo Base', 'verbose_name_plural': 'Modelos Base'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_user',
            new_name='author',
        ),
        migrations.AddField(
            model_name='comment',
            name='is_internal',
            field=models.BooleanField(default=True, help_text='Si el comentario es visible solo para el equipo interno'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(),
        ),
    ]
