# Generated by Django 4.2 on 2025-11-19 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_commentattachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterModelOptions(
            name='commentattachment',
            options={'verbose_name': 'Archivo Comentario', 'verbose_name_plural': 'Archivos Comentarios'},
        ),
    ]
