# Generated by Django 4.2 on 2025-06-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractionlog',
            name='action',
            field=models.CharField(choices=[('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('create', 'Creación'), ('update', 'Actualización'), ('delete', 'Eliminación'), ('view', 'Visualización'), ('download', 'Descarga'), ('upload', 'Subida'), ('assign', 'Asignación'), ('change_state', 'Cambio de estado'), ('custom', 'Personalizado')], default='custom', max_length=50),
        ),
    ]
