# Generated by Django 4.2 on 2025-06-17 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_options_notification_is_read_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Notificacion', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.AlterModelOptions(
            name='notificationtype',
            options={'verbose_name': 'Tipo de notificacion', 'verbose_name_plural': 'Tipos de notificaciones'},
        ),
    ]
