# Generated by Django 4.2 on 2025-06-24 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_rename_user_notification_to_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notificacion', 'verbose_name_plural': 'Notificaciones'},
        ),
    ]
